// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utsjwnjiyvshfaurulfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0c2p3bmppeXZzaGZhdXJ1bGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMjczMjgsImV4cCI6MjA4ODkwMzMyOH0.xxfmRoPv0I9CY8T8dt16Zk3pkRpILoWgxyEk6zPkWws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});